---
# tasks file for db
#
- name: Install MySQL
  apt:
    name: '{{ item }}'
    state: latest
  notify: restart mysql

  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Create database
  mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Create user for the database
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    encrypted: yes
    priv: '{{ db_name }}.*:ALL'
    state: present
