---
# tasks file for common
#
- name: Change repository Ubuntu 18.04
  copy:
    src: sources.list
    dest: /etc/apt/
    backup: yes

- name: Update repository and Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Setup timezone to Asia/Jakarta
  timezone:
    name: Asia/Jakarta

